### ISSUE TITLE
View, PDF and images attachments in Deck not working

### ISSUE THREAD

**Issue by ioscanner** [StCyr/deck-react-native#19] opened 2022-10-25 14:30 UTC
Update:  The change notes say attachments are viewable.  Guess it is not working.  I am testing on iOS 16.1

So far the latest update fixed the duplicate labels, Now the only thing left is to be able to view PDF and images uploaded to a card in the deck.  Maybe download a document that is attached so the user can edit on the device and upload it again.  Really would be nice if it opened the document in NextCloud app so you can edit there.  But then they would need to upload via nextcloud then link in the Deck from Nextcloud share so you would have the path.  But for now would be grateful to just view PDF and images. 

Not sure if they have a way to pass a document to Nextcloud on iOS.

Thanks again great job!

**Comment by ioscanner** [comment] 2022-11-02 13:29
I understand how the UI works.  Yes, when I long click Attachments I can upload and that works and the date is always January 20,1970 can this be the correct date of the upload?

To view I click on the attachment.  It doesn't do anything.  For any document.  PDF, jpg, png, doc

The other thing I notice is color for the attachment name in Dark theme it is all dark grey print on a dark background making it very difficult to read.  But the User that uploaded the attachment is in white.   Same for Description it is dark grey print on black background.  When in white theme all print is black.  But the labels that are dark use dark print so those are hard to read.

I have tried from both iOS 15 and iOS 16.  My ipad is still on iOS 15. 

This is all the issues I have seen so far.  If you have a testflight version I can test the other version if needed.

**Comment by StCyr** [comment] 2022-11-02 14:09
Hi,

thanks for the update: I'm building version 0.12.1 that will probably fix your original issue.

>I understand how the UI works. Yes, when I long click Attachments I can upload and that works and the date is always January 20,1970 can this be the correct date of the upload?
You're right. I'll fix this => https://framagit.org/StCyr/deck-react-native/-/issues/85

>The other thing I notice is color for the attachment name in Dark theme it is all dark grey print on a dark background making it very difficult to read. But the User that uploaded the attachment is in white. Same for Description it is dark grey print on black background. When in white theme all print is black. But the labels that are dark use dark print so those are hard to read.
I've noticed and fixed that already

>This is all the issues I have seen so far. If you have a testflight version I can test the other version if needed.
I don't use testflight yet...

Thanks for your testing :-)

**Comment by StCyr** [comment] 2022-11-02 17:25
It turns out I'm using testflight. So, if you want to participate, just send me your email (my email address is in the README.md file).

The new version is now reviewed by Apple. It should be available tomorrow, or the day after at the latest.

**Comment by ioscanner** [comment] 2022-11-03 03:34
I loaded the latest version.  I can't open any attachments now.  It gives Error: File 'file:/var/mobile/Containers/...  When I click the look icon.

The Description text is still dark grey when viewing the card.

**Comment by StCyr** [comment] 2022-11-03 08:43
ok, thanks for the follow-up.

I'm now publishing version 0.12.2 which fixes an issue with attachment names having blank spaces in their name; maybe that's your issue.

>The Description text is still dark grey when viewing the card.

Oh... I'll have to confirm that later (don't have access to my development environment today)

**Comment by ioscanner** [comment] 2022-11-03 13:43
Yes, some tests had spaces.  The other thing I notice is anything else that I try to open it just goes to the name, file type,and file size with the share icon screen.  As if it is trying to download the file, instead of opening the file to view.

![IMG_1667482740875](https://user-images.githubusercontent.com/26411524/199736230-16ea224b-2dbd-496a-a651-a1666cef63ff.jpg)

**Comment by StCyr** [comment] 2022-11-03 16:08
version 0.12.2 is released

**Comment by ioscanner** [comment] 2022-11-03 16:42
Tested.  Attachments work now!

Two issues I see:

- After you select file to upload it gives no status just sends back to card.  I am sure people will go back in thinking it didn't do anything.  It seems to take about 6-10 seconds or more for the attachment to show up depending on the file size.  Maybe a popup that says upload complete, attachment will show shortly. Could just hold the screen while you wait for attachment to show.
- Description content: the text is still dark almost black when in dark mode you can't read.  Text should be white like other fields when in dark mode and black when in light mode.

I will do more testing, but so far I think that all major issues that impact usability.

**Comment by StCyr** [comment] 2022-11-04 14:19
>    After you select file to upload it gives no status just sends back to card. I am sure people will go back in thinking it didn't do anything. It seems to take about 6-10 seconds or more for the attachment to show up depending on the file size. Maybe a popup that says upload complete, attachment will show shortly. Could just hold the screen while you wait for attachment to show.

Yes, There's normally a spinner but I've issues displaying it now that the attachment panel is a component of its own => https://framagit.org/StCyr/deck-react-native/-/issues/81

 >  Description content: the text is still dark almost black when in dark mode you can't read. Text should be white like other fields when in dark mode and black when in light mode.

Confirmed => https://framagit.org/StCyr/deck-react-native/-/issues/88

**Comment by StCyr** [comment] 2022-11-09 09:22
all remaining issue registered elsewhere => closing this one

**Closed by StCyr** 2022-11-09 09:22 UTC
